from model_utils.utils import prepare_vllm_tokenizer

from huggingface_hub import snapshot_download

from vllm import LLM, SamplingParams
from vllm.lora.request import LoRARequest


adapter_name= "liuhaozhe6788/mistralai_Mistral-7B-Instruct-v0.3-peftq_proj_k_proj_v_proj_o_proj-bs1-ne1"
model_name = "mistralai/Mistral-7B-Instruct-v0.3"

passage_query = """     ###Passage: the following table presents var with respect to our trading activities , as measured by our var methodology for the periods indicated : value-at-risk .

years ended december 31 ( inmillions )|2008 annual average|2008 maximum|2008 minimum|2008 annual average|2008 maximum|minimum
foreign exchange products|$ 1.8|$ 4.7|$ .3|$ 1.8|$ 4.0|$ .7
interest-rate products|1.1|2.4|.6|1.4|3.7|.1

we back-test the estimated one-day var on a daily basis .
this information is reviewed and used to confirm that all relevant trading positions are properly modeled .
for the years ended december 31 , 2008 and 2007 , we did not experience any actual trading losses in excess of our end-of-day var estimate .
asset and liability management activities the primary objective of asset and liability management is to provide sustainable and growing net interest revenue , or nir , under varying economic environments , while protecting the economic values of our balance sheet assets and liabilities from the adverse effects of changes in interest rates .
most of our nir is earned from the investment of deposits generated by our core investment servicing and investment management businesses .
we structure our balance sheet assets to generally conform to the characteristics of our balance sheet liabilities , but we manage our overall interest-rate risk position in the context of current and anticipated market conditions and within internally-approved risk guidelines .
our overall interest-rate risk position is maintained within a series of policies approved by the board and guidelines established and monitored by alco .
our global treasury group has responsibility for managing state street 2019s day-to-day interest-rate risk .
to effectively manage the consolidated balance sheet and related nir , global treasury has the authority to take a limited amount of interest-rate risk based on market conditions and its views about the direction of global interest rates over both short-term and long-term time horizons .
global treasury manages our exposure to changes in interest rates on a consolidated basis organized into three regional treasury units , north america , europe and asia/pacific , to reflect the growing , global nature of our exposures and to capture the impact of change in regional market environments on our total risk position .
our investment activities and our use of derivative financial instruments are the primary tools used in managing interest-rate risk .
we invest in financial instruments with currency , repricing , and maturity characteristics we consider appropriate to manage our overall interest-rate risk position .
in addition to on-balance sheet assets , we use certain derivatives , primarily interest-rate swaps , to alter the interest-rate characteristics of specific balance sheet assets or liabilities .
the use of derivatives is subject to alco-approved guidelines .
additional information about our use of derivatives is in note 17 of the notes to consolidated financial statements included in this form 10-k under item 8 .
as a result of growth in our non-u.s .
operations , non-u.s .
dollar denominated customer liabilities are a significant portion of our consolidated balance sheet .
this growth results in exposure to changes in the shape and level of non-u.s .
dollar yield curves , which we include in our consolidated interest-rate risk management process .
because no one individual measure can accurately assess all of our exposures to changes in interest rates , we use several quantitative measures in our assessment of current and potential future exposures to changes in interest rates and their impact on net interest revenue and balance sheet values .
net interest revenue simulation is the primary tool used in our evaluation of the potential range of possible net interest revenue results that could occur under a variety of interest-rate environments .
we also use market valuation and duration analysis to assess changes in the economic value of balance sheet assets and liabilities caused by assumed changes in interest rates .
finally , gap analysis 2014the difference between the amount of balance sheet assets and liabilities re-pricing within a specified time period 2014is used as a measurement of our interest-rate risk position. .
    ###Question: what is the average variance of the value at risk of each 2008 section? ( $ )"""
zero_shot_prompt = "<s>[INST] {}{} [/INST]".format("Read the following passage and then write python code to answer the question:   ", f"""    {passage_query}
    ###Instructions: First, identify entities required to answer the question. Extract the identified entities and store in python variables. Then perform calculations with the entities and strictly store the answer to the python variable "ans". Python code must end after the variable "ans" is defined. Comments must begin with character "#".
    ###Python
    """)
ft_prompt = "<s>[INST] {}{} [/INST]".format("Read the following passage and then write python code to answer the question:   ", f"""    {passage_query}
    ###Python
""")

llm = LLM(model=model_name, tokenizer=adapter_name, enable_lora=True, max_lora_rank=512)
llm.set_tokenizer(prepare_vllm_tokenizer(llm.get_tokenizer(), padding_side="left"))
lora_path = snapshot_download(repo_id=adapter_name)
outputs = llm.generate(
    [ft_prompt], 
    sampling_params=SamplingParams(temperature=0.0, top_p=0.9, max_tokens=1000),
    lora_request=LoRARequest(
        "FinQA_adapter", 1, lora_path)
)
print("Fine-tuned model with vllm:")
ans = outputs[0].outputs[0].text
# Post-process: cut off everything after '###End Python' if it exists
end_marker = "###End Python"
if end_marker in ans:
    ans = ans.split(end_marker)[0] + "\n" + end_marker
print(ans)
print("-"*100)

llm = LLM(model=model_name)
llm.set_tokenizer(prepare_vllm_tokenizer(llm.get_tokenizer(), padding_side="left"))
outputs = llm.generate(
    [zero_shot_prompt], 
    sampling_params=SamplingParams(temperature=0.0, top_p=0.9, max_tokens=1000),
)
print("Zero-shot model with vllm:")
ans = outputs[0].outputs[0].text
# Post-process: cut off everything after '###End Python' if it exists
end_marker = "###End Python"
if end_marker in ans:
    ans = ans.split(end_marker)[0] + "\n" + end_marker
print(ans)
print("-"*100)